on:
  push:
    branches:
      - 'main'
      - 'develop'
    
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9'

      - name: Install packages
        run: dotnet clean && dotnet restore
      
      - name: Build
        run: cd src/Common && dotnet pack && cd ../../
        
      - name: Publish
        run: 
          cd src/Common/bin/Release && 
          dotnet nuget push *.nupkg --source https://nuget.pkg.github.com/UnspokenTeam/index.json --api-key ${GITHUB_TOKEN}
        env: 
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}